// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSO2sqgtpviA9hqeeX7dTwEr3J5cFjcBg',
    appId: '1:680814119355:web:90cf73ffe7795394265c9e',
    messagingSenderId: '680814119355',
    projectId: 'bcmedicalrecords',
    authDomain: 'bcmedicalrecords.firebaseapp.com',
    storageBucket: 'bcmedicalrecords.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDaXFvynF7jVQXOBd_SWGi6oui51yEqr0',
    appId: '1:680814119355:android:64dc5b84a442c082265c9e',
    messagingSenderId: '680814119355',
    projectId: 'bcmedicalrecords',
    storageBucket: 'bcmedicalrecords.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC29m62mj9nYTMItwUSqAI1d7NrmHEKuQI',
    appId: '1:680814119355:ios:740160519c95d4e0265c9e',
    messagingSenderId: '680814119355',
    projectId: 'bcmedicalrecords',
    storageBucket: 'bcmedicalrecords.appspot.com',
    iosBundleId: 'com.example.bcmedicalrecords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC29m62mj9nYTMItwUSqAI1d7NrmHEKuQI',
    appId: '1:680814119355:ios:0ced8f0d6ddb7587265c9e',
    messagingSenderId: '680814119355',
    projectId: 'bcmedicalrecords',
    storageBucket: 'bcmedicalrecords.appspot.com',
    iosBundleId: 'com.example.bcmedicalrecords.RunnerTests',
  );
}
